name: om_elnour_choir
description: "A new Flutter project."
publish_to: 'none'

version: 3.0.0+300

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  http: ^1.4.0
  cloud_firestore: ^5.6.11
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  shared_preferences: ^2.5.3
  in_app_update: ^4.2.3
  flutter_launcher_icons: ^0.14.4
  audioplayers: ^6.5.0
  audio_service: ^0.18.18
  audio_session: ^0.2.2
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.0
  just_audio: ^0.10.4
  just_audio_background: ^0.0.1-beta.17
  firebase_storage: ^12.4.9
  image_picker: ^1.1.2
  firebase_messaging: ^15.2.9
  google_mobile_ads: ^5.1.0
  url_launcher: ^6.3.1
  intl: ^0.20.2
  firebase_analytics: ^11.5.2
  flutter_secure_storage: ^9.2.4
  flutter_cache_manager: ^3.4.1
  cached_network_image: ^3.4.1
  flutter_inappwebview: ^6.1.5
  flutter_local_notifications: ^19.3.0
  rxdart: ^0.28.0
  permission_handler: ^11.4.0
  equatable: ^2.0.7
  sqflite: ^2.4.2
  firebase_remote_config: ^5.4.7
  package_info_plus: ^8.3.0
  file_picker: ^10.2.0
  country_code_picker: ^3.3.0
  pin_code_fields: ^8.0.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  get_it: ^8.0.3
  firebase_app_check: ^0.3.2+9
  cupertino_icons: ^1.0.8
  flutter_upgrade_version: ^1.1.8
  connectivity_plus: ^6.1.4
  share_plus: ^11.0.0
  path_provider: ^2.1.5
  headset_connection_event: ^4.0.2
  android_intent_plus: ^5.3.0
  ignore_battery_optimization: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/appIcon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/appIcon.png"
